#%RAML 1.0 Trait
headers:
  client_id:
    description: The Client ID allocated by MuleSoft when you request access.
    type: string
    required: true
    example: 3f7e39a8b2db4cf4bc865cc01fc9398b
  client_secret:
      description: The Client Secret allocated by MuleSoft when you request access.
      type: string
      required: true
      example: C257B47566734B9B9E76403d7b5d0a66